version: '3'
services:
  app:
    container_name: tythm-app
    image: node:16.13.1-alpine
    volumes:
      - .:/app:cached
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
